// <auto-generated />
using BlackJackGameApi.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlackJackGameApi.Migrations
{
    [DbContext(typeof(PlayingCardDatabaseContext))]
    partial class PlayingCardDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("CardEntityDeckEntity", b =>
                {
                    b.Property<int>("CardsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DecksId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CardsId", "DecksId");

                    b.HasIndex("DecksId");

                    b.ToTable("CardEntityDeckEntity");
                });

            modelBuilder.Entity("StackImplementation_November.Models.PlayingCard.CardEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Color")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Suit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = 0,
                            Suit = 0,
                            Value = 1
                        },
                        new
                        {
                            Id = 2,
                            Color = 0,
                            Suit = 0,
                            Value = 2
                        },
                        new
                        {
                            Id = 3,
                            Color = 0,
                            Suit = 0,
                            Value = 3
                        },
                        new
                        {
                            Id = 4,
                            Color = 0,
                            Suit = 0,
                            Value = 4
                        },
                        new
                        {
                            Id = 5,
                            Color = 0,
                            Suit = 0,
                            Value = 5
                        },
                        new
                        {
                            Id = 6,
                            Color = 0,
                            Suit = 0,
                            Value = 6
                        },
                        new
                        {
                            Id = 7,
                            Color = 0,
                            Suit = 0,
                            Value = 7
                        },
                        new
                        {
                            Id = 8,
                            Color = 0,
                            Suit = 0,
                            Value = 8
                        },
                        new
                        {
                            Id = 9,
                            Color = 0,
                            Suit = 0,
                            Value = 9
                        },
                        new
                        {
                            Id = 10,
                            Color = 0,
                            Suit = 0,
                            Value = 10
                        },
                        new
                        {
                            Id = 11,
                            Color = 0,
                            Suit = 0,
                            Value = 11
                        },
                        new
                        {
                            Id = 12,
                            Color = 0,
                            Suit = 0,
                            Value = 12
                        },
                        new
                        {
                            Id = 13,
                            Color = 0,
                            Suit = 0,
                            Value = 13
                        },
                        new
                        {
                            Id = 14,
                            Color = 0,
                            Suit = 0,
                            Value = 14
                        },
                        new
                        {
                            Id = 15,
                            Color = 0,
                            Suit = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 16,
                            Color = 0,
                            Suit = 1,
                            Value = 2
                        },
                        new
                        {
                            Id = 17,
                            Color = 0,
                            Suit = 1,
                            Value = 3
                        },
                        new
                        {
                            Id = 18,
                            Color = 0,
                            Suit = 1,
                            Value = 4
                        },
                        new
                        {
                            Id = 19,
                            Color = 0,
                            Suit = 1,
                            Value = 5
                        },
                        new
                        {
                            Id = 20,
                            Color = 0,
                            Suit = 1,
                            Value = 6
                        },
                        new
                        {
                            Id = 21,
                            Color = 0,
                            Suit = 1,
                            Value = 7
                        },
                        new
                        {
                            Id = 22,
                            Color = 0,
                            Suit = 1,
                            Value = 8
                        },
                        new
                        {
                            Id = 23,
                            Color = 0,
                            Suit = 1,
                            Value = 9
                        },
                        new
                        {
                            Id = 24,
                            Color = 0,
                            Suit = 1,
                            Value = 10
                        },
                        new
                        {
                            Id = 25,
                            Color = 0,
                            Suit = 1,
                            Value = 11
                        },
                        new
                        {
                            Id = 26,
                            Color = 0,
                            Suit = 1,
                            Value = 12
                        },
                        new
                        {
                            Id = 27,
                            Color = 0,
                            Suit = 1,
                            Value = 13
                        },
                        new
                        {
                            Id = 28,
                            Color = 0,
                            Suit = 1,
                            Value = 14
                        },
                        new
                        {
                            Id = 29,
                            Color = 1,
                            Suit = 2,
                            Value = 1
                        },
                        new
                        {
                            Id = 30,
                            Color = 1,
                            Suit = 2,
                            Value = 2
                        },
                        new
                        {
                            Id = 31,
                            Color = 1,
                            Suit = 2,
                            Value = 3
                        },
                        new
                        {
                            Id = 32,
                            Color = 1,
                            Suit = 2,
                            Value = 4
                        },
                        new
                        {
                            Id = 33,
                            Color = 1,
                            Suit = 2,
                            Value = 5
                        },
                        new
                        {
                            Id = 34,
                            Color = 1,
                            Suit = 2,
                            Value = 6
                        },
                        new
                        {
                            Id = 35,
                            Color = 1,
                            Suit = 2,
                            Value = 7
                        },
                        new
                        {
                            Id = 36,
                            Color = 1,
                            Suit = 2,
                            Value = 8
                        },
                        new
                        {
                            Id = 37,
                            Color = 1,
                            Suit = 2,
                            Value = 9
                        },
                        new
                        {
                            Id = 38,
                            Color = 1,
                            Suit = 2,
                            Value = 10
                        },
                        new
                        {
                            Id = 39,
                            Color = 1,
                            Suit = 2,
                            Value = 11
                        },
                        new
                        {
                            Id = 40,
                            Color = 1,
                            Suit = 2,
                            Value = 12
                        },
                        new
                        {
                            Id = 41,
                            Color = 1,
                            Suit = 2,
                            Value = 13
                        },
                        new
                        {
                            Id = 42,
                            Color = 1,
                            Suit = 2,
                            Value = 14
                        },
                        new
                        {
                            Id = 43,
                            Color = 1,
                            Suit = 3,
                            Value = 1
                        },
                        new
                        {
                            Id = 44,
                            Color = 1,
                            Suit = 3,
                            Value = 2
                        },
                        new
                        {
                            Id = 45,
                            Color = 1,
                            Suit = 3,
                            Value = 3
                        },
                        new
                        {
                            Id = 46,
                            Color = 1,
                            Suit = 3,
                            Value = 4
                        },
                        new
                        {
                            Id = 47,
                            Color = 1,
                            Suit = 3,
                            Value = 5
                        },
                        new
                        {
                            Id = 48,
                            Color = 1,
                            Suit = 3,
                            Value = 6
                        },
                        new
                        {
                            Id = 49,
                            Color = 1,
                            Suit = 3,
                            Value = 7
                        },
                        new
                        {
                            Id = 50,
                            Color = 1,
                            Suit = 3,
                            Value = 8
                        },
                        new
                        {
                            Id = 51,
                            Color = 1,
                            Suit = 3,
                            Value = 9
                        },
                        new
                        {
                            Id = 52,
                            Color = 1,
                            Suit = 3,
                            Value = 10
                        },
                        new
                        {
                            Id = 53,
                            Color = 1,
                            Suit = 3,
                            Value = 11
                        },
                        new
                        {
                            Id = 54,
                            Color = 1,
                            Suit = 3,
                            Value = 12
                        },
                        new
                        {
                            Id = 55,
                            Color = 1,
                            Suit = 3,
                            Value = 13
                        },
                        new
                        {
                            Id = 56,
                            Color = 1,
                            Suit = 3,
                            Value = 14
                        });
                });

            modelBuilder.Entity("StackImplementation_November.Models.PlayingCard.DeckEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("CardEntityDeckEntity", b =>
                {
                    b.HasOne("StackImplementation_November.Models.PlayingCard.CardEntity", null)
                        .WithMany()
                        .HasForeignKey("CardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StackImplementation_November.Models.PlayingCard.DeckEntity", null)
                        .WithMany()
                        .HasForeignKey("DecksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
